[project]
name = "exrates-fetching"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "duckdb>=1.4.3",
    "polars>=1.36.1",
    "pyarrow>=22.0.0",
    "requests>=2.32.5",
]
